#!/bin/bash

pandoc \
  --variable mainfont="DejaVu Sans" \
  --variable monofont="DejaVu Sans Mono" \
  --variable fontsize=11pt \
  --variable geometry:"top=1.5cm, bottom=2.5cm, left=1.5cm, right=1.5cm" \
  --variable geometry:a4paper \
  --table-of-contents \
  --number-sections \
  -f markdown ./src/$1.md \
  --pdf-engine=xelatex \
  -o ./out/$1.pdf

